// ** Next Components
import Head from 'next/head'

// ** App Components
import Navbar from '../components/Navbar'
import Presentation from '../components/Presentation'
import AboutMe from '../components/AboutMe'

// ** App data
import Data from "../constants/info"
import Skills from '../components/Skills'
import Footer from '../components/Footer'
import Projects from '../components/Projects'

const castStringToVariable = ( largeString, parameter ) => {
  return largeString.replace("%s", parameter)
}

export default function Home({
  appData
}) {

  return (
    <div>
      <Head>
        <title>JoseUgal - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Presentation 
        imgUrl={appData.illustrations.main} 
        name={appData.name}
        job={appData.specialization}
      />
      <AboutMe description={castStringToVariable(appData.about, appData.name)} />
      <Skills data={appData.skills}/>
      <Projects data={appData.projects} />
      <Footer />
    </div>
  )
}

export const getStaticProps = async () => {
    return {
      props: {
        appData: Data
      }
    }
}

