// ** React utils
import { useState } from "react"

// ** Next Components
import Head from 'next/head'

// ** App Components
import Navbar from '../components/Navbar'
import Presentation from '../components/Presentation'
import AboutMe from '../components/AboutMe'

// ** App data
import Data from "../constants/info"
import Skills from '../components/Skills'
import Footer from '../components/Footer'
import Projects from '../components/Projects'
import MobileMenu from "../components/MobileMenu"
import Services from "../components/Services"

const castStringToVariable = ( largeString, parameter ) => {
  return largeString.replace("%s", parameter)
}

export default function Home({
  appData
}) {
  const [defaultLanguage, setDefaultLanguage] = useState('es')


  return (
    <div>
      <Head>
        <title>JoseUgal - {appData.title[defaultLanguage]}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MobileMenu 
        info={appData}
        lng={defaultLanguage}
        setDefaultLanguage={setDefaultLanguage}
      />
      <Navbar 
        info={appData}
        lng={defaultLanguage}
        setDefaultLanguage={setDefaultLanguage}
      />

      <Presentation 
        info={appData}
        lng={defaultLanguage}
      />

      <AboutMe 
        description={appData.about.text[defaultLanguage]}
        title={appData.about.title[defaultLanguage]}
        sDownload={appData.sentences.download[defaultLanguage]}
      />

      <Skills data={appData.skills.data} text={appData.skills.text[defaultLanguage]} title={appData.skills.title[defaultLanguage]}/>
      
      <Services 
        info={appData}
        lng={defaultLanguage}
      />
      
      <Projects title={appData.projects.title[defaultLanguage]} data={appData.projects.data} lng={defaultLanguage} /> 
      
      <Footer />
    </div>
  )
}

export const getStaticProps = async () => {
    return {
      props: {
        appData: Data
      }
    }
}

